name: seather
description: A weather app that just works.
publish_to: 'none'
version: 99.99.99+99

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  envied: ^0.3.0+3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.5.0
  geolocator: ^10.0.0
  weather_icons: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
